spring.application.name=HospitalManagement

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/demo_schema
spring.datasource.username=root
spring.datasource.password=$Einstein01Albert

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# For Data Seeding
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

# MySQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Optional (recommended)
#spring.jpa.open-in-view=false

# API Versioning
server.servlet.context-path=/api/v1

# Security Config
spring.security.user.name=abc
spring.security.user.password=123

# JWT Secret Key
jwt.secretKey=vurgvdva1v6s5vv1919b119h19afsdfgr1vsv

# OAuth Configuration (Some third party open autorization are by default configured in Spring Security i.e. google, facebook, github, etc.)
# (We can also write it as written in application.yml)
spring.security.oauth2.client.registration.google.client-id=client-id
spring.security.oauth2.client.registration.google.client-secret=client-secret